import { StyleSheet } from "react-native";

export const DetailsStyle = StyleSheet.create({
    modalBackground: {
        flex: 1,
        backgroundColor: "#f2b807",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    modalContent: {
        width: "90%",
        backgroundColor: "#ffffff",
        borderRadius: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        alignItems: "center",
        alignSelf: "center",
    },
    pokemonImage: {
        width: 200,
        height: 200,
        marginBottom: 20,
        alignSelf: "center",
        borderRadius: 10,
    },
    pokemonName: {
        fontSize: 28,
        fontWeight: "bold",
        marginBottom: 5,
        textAlign: "center",
        color: "#333",
    },
    pokemonSpecies: {
        fontSize: 16,
        fontWeight: "500",
        marginBottom: 15,
        textAlign: "center",
        color: "#555",
    },
    closeButton: {
        backgroundColor: "#e74c3c",
        padding: 12,
        borderRadius: 10,
        alignSelf: "center",
        marginTop: 20,
    },
    closeButtonText: {
        color: "#fff",
        fontWeight: "bold",
        textAlign: "center",
        fontSize: 16,
    },
    favoriteButton: {
        backgroundColor: '#FFD700',
        padding: 10,
        borderRadius: 5,
        margin: 10,
    },
    favoriteButtonText: {
        fontSize: 16,
        color: '#000',
        textAlign: 'center',
    },

    abilitiesSection: {
        marginTop: 10,
        padding: 15,
        backgroundColor: "#f8f9fa",
        borderRadius: 15,
        width: "100%",
        borderWidth: 1,
        borderColor: "#ddd",
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 10,
        color: "#444",
        textAlign: "left",
    },
    abilityText: {
        fontSize: 14,
        color: "#555",
        marginVertical: 5,
    },
    abilityContainer: {
        marginVertical: 10,
        padding: 10,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 10,
        backgroundColor: "#ffffff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 3,
    },
    abilityName: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 5,
        color: "#333",
    },
    abilityEffect: {
        fontSize: 14,
        color: "#555",
        lineHeight: 18,
    },
    topNav: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 20,
    },
    modalScroll: {
        width: "100%",
    },
});
